#!/usr/bin/env python3
import logging
import click
from src.slackboxlive import SlackBoxLive
from src import logger

@click.command()
@click.option('--api-key', help='API Key provided by xboxapi.com')
@click.option('--user-id', help='User ID of the account to use for notification')
def init(backup, api_key, user_id):
    slackboxlive = SlackBoxLive(api_key, user_id)

if __name__ == '__main__':
    try:
        logger.initialize_logger()
        init()
    except Exception as e:
        logger = logging.getLogger("slackboxlive")
        logging.critical("Unhandled exception: {}".format(e), exc_info=True)
        raise